export const fullMatchCommentary: Record<number, string> = {
  0: "[SCOUT]: Match kickoff. Analyzing starting formations... Both teams contesting the midfield.",
  1: "[ORACLE]: Midfield possession is 50/50. No immediate context gaps detected.",
  2: "[SCOUT]: Morocco is beginning to overload the left flank. Canada struggling to maintain defensive shape against the high press.",
  3: "[SCOUT]: Morocco intercepts a sloppy pass! It's a rapid counter-attack, Ziyech has space! Attacking momentum is completely overwhelming for the home side.",
  4: "[SCOUT]: GOAL! Unbelievable error by Canadian goalkeeper Milan Borjan. He passes straight to Hakim Ziyech who chips it in from 30 yards. Morocco 1-0.",
  5: "[ORACLE]: Goal registered. TxOdds shifting heavily towards Morocco. Re-evaluating xG momentum.",
  6: "[SCOUT]: Canada attempts to build from the back but looks nervous. Passes are erratic.",
  7: "[ORACLE]: Nervousness detected in Canada's defensive third. High probability of another turnover.",
  8: "[SCOUT]: Morocco pressing very high. Ziyech is dictating the tempo.",
  9: "[SCOUT]: Long ball played forward by Canada, goes out for a goal kick.",
  10: "[ORACLE]: Canada struggling to bypass the high press. TxOdds underestimating Morocco's dominance here.",
  11: "[SCOUT]: A slow buildup in the center circle. Tempo dropping.",
  12: "[ORACLE]: Adjusting pace metric. Expected goals in the next 10 minutes decreasing.",
  13: "[SCOUT]: Canada finds some space on the left flank. Alphonso Davies accelerating.",
  14: "[ORACLE]: Davies on the ball. Cross success rate is 32%. Heightening alert level.",
  15: "[SCOUT]: Morocco looks extremely dangerous on the counter-attack. Canada losing possession under pressure.",
  16: "[ORACLE]: Counter-attack threat is severe. The mathematical odds for Over 1.5 are dropping, but the context suggests a goal is imminent.",
  17: "[SCOUT]: Morocco intercepts a loose pass and immediately transitions forward.",
  18: "[SCOUT]: Foul just outside the box! Free kick awarded to Morocco, 25 yards out.",
  19: "[ORACLE]: Free kick detected. Analyzing player stats... Hakimi is standing over the ball. His last 5 free kicks have been on target. Threat level critical.",
  20: "[SCOUT]: Hakimi strikes it... saved by the keeper! Corner kick.",
  21: "[ORACLE]: Corner kick clearance rate for Canada is poor today. Maintaining high threat alert.",
  22: "[SCOUT]: Cleared away. A long ball is played forward but it goes out for a goal kick.",
  23: "[SCOUT]: GOAL! Hakimi plays a brilliant long pass to En-Nesyri, who outruns the defense and fires it past the keeper! Morocco 2-0.",
  24: "[ORACLE]: Goal confirmed. The context gap successfully predicted the attacking momentum.",
  25: "[SCOUT]: Canada seems shell-shocked by the second goal.",
  26: "[ORACLE]: Tactical collapse detected. Win probability for Canada approaches 0%.",
  27: "[SCOUT]: Both teams are assessing each other's tactical shape.",
  28: "[SCOUT]: The ball is heavily contested in the midfield area.",
  29: "[SCOUT]: Players are slowing the pace down with short passes.",
  30: "[SCOUT]: A throw-in is awarded after a physical tackle on the wing.",
  31: "[ORACLE]: Match settling into a low-event state. Adjusting Under 3.5 probabilities.",
  32: "[SCOUT]: Goalkeeper distributes the ball to the center backs.",
  33: "[SCOUT]: Canada is finally starting to build some attacks but the final pass is lacking.",
  34: "[ORACLE]: Canadian possession increasing, but entirely non-threatening (xG per pass < 0.01).",
  35: "[SCOUT]: Morocco is defending deep, absorbing pressure.",
  36: "[ORACLE]: Low block defensive formation recognized. Morocco is protecting the lead.",
  37: "[SCOUT]: The ball is heavily contested in the midfield area.",
  38: "[SCOUT]: Canada is throwing everyone forward! Alphonso Davies creates massive space on the wing.",
  39: "[SCOUT]: Canada forces another turnover in the final third! A goal is imminent for the away side! Incredible attacking momentum.",
  40: "[SCOUT]: OWN GOAL! Sam Adekugbe crosses the ball for Canada, and Nayef Aguerd accidentally deflects it past his own goalkeeper! Canada 1-2.",
  41: "[ORACLE]: Freak event detected. Own goals cause massive market volatility. Pausing aggressive trades until structure returns.",
  42: "[SCOUT]: The crowd comes alive again as Canada finds a lifeline.",
  43: "[ORACLE]: Momentum shift calculated. NLP sentiment for Canada is suddenly positive.",
  44: "[SCOUT]: Halftime. Morocco 2 - 1 Canada. The game has been highly volatile.",
  45: "[ORACLE]: Halftime analysis running. Adjusting second-half baseline probabilities.",
  46: "[SCOUT]: Halftime break. Players head to the tunnels.",
  47: "[ORACLE]: Processing historical 2nd half data for these exact team lineups...",
  48: "[SCOUT]: Halftime break. Fans are catching their breath.",
  49: "[SCOUT]: Players are returning to the pitch.",
  50: "[SCOUT]: Second half begins. Canada looks energized and is pressing higher.",
  51: "[ORACLE]: High press detected. Canada taking risks. Space opening up behind their defense.",
  52: "[SCOUT]: The ball is heavily contested in the midfield area.",
  53: "[SCOUT]: A throw-in is awarded after a physical tackle on the wing.",
  54: "[SCOUT]: The referee plays advantage after a slight foul in the center circle.",
  55: "[ORACLE]: Match tempo is chaotic. High frequency of fouls disrupting flow.",
  56: "[SCOUT]: Goalkeeper distributes the ball to the center backs.",
  57: "[SCOUT]: The defensive line pushes up to catch the attackers offside.",
  58: "[ORACLE]: High defensive line confirmed. En-Nesyri's pace could exploit this.",
  59: "[SCOUT]: The ball is heavily contested in the midfield area.",
  60: "[SCOUT]: Players are slowing the pace down with short passes.",
  61: "[SCOUT]: A throw-in is awarded after a physical tackle on the wing.",
  62: "[ORACLE]: Scanning for context gaps... Odds are stabilizing. No significant edge found.",
  63: "[SCOUT]: Goalkeeper distributes the ball to the center backs.",
  64: "[SCOUT]: A long ball is played forward but it goes out for a goal kick.",
  65: "[SCOUT]: Morocco makes defensive substitutions, bringing on Amallah and Aboukhlal.",
  66: "[ORACLE]: Substitutions logged. Morocco shifting to a 5-at-the-back formation. Under markets heavily favored.",
  67: "[SCOUT]: Both teams are assessing each other's tactical shape.",
  68: "[SCOUT]: The ball is heavily contested in the midfield area.",
  69: "[SCOUT]: Players are slowing the pace down with short passes.",
  70: "[SCOUT]: Corner kick for Canada. The tall center backs are moving into the box.",
  71: "[ORACLE]: Analyzing corner kick routines... Hutchinson is the primary target.",
  72: "[SCOUT]: INCREDIBLE OFF THE BAR! Hutchinson's header crashes off the underside of the crossbar, bounces on the line, and is cleared!",
  73: "[ORACLE]: Massive xG spike (0.85). Goal-line technology confirms no goal. Market is panicking, odds fluctuating wildly.",
  74: "[SCOUT]: Canada is furious, pressing relentlessly now.",
  75: "[ORACLE]: Extreme attacking momentum for Canada. Context indicates a high chance of a late equalizer.",
  76: "[SCOUT]: The defensive line pushes up to catch the attackers offside.",
  79: "[SCOUT]: Morocco makes two defensive substitutions to secure the lead.",
  80: "[SCOUT]: Morocco has transitioned into a deep low block. They are overtly wasting time on every set piece.",
  81: "[ORACLE]: Extreme defensive adjustments confirmed. Expected goals dropping near zero.",
  82: "[SCOUT]: The game is completely stalled in the midfield. No attacking intent from the home side.",
  83: "[SCOUT]: Goalkeeper distributes the ball to the center backs.",
  84: "[SCOUT]: A long ball is played forward but it goes out for a goal kick.",
  85: "[ORACLE]: Time decay algorithm active. Win probability for Morocco increasing rapidly with every passing second.",
  86: "[SCOUT]: Both teams are assessing each other's tactical shape.",
  87: "[SCOUT]: The ball is heavily contested in the midfield area.",
  88: "[SCOUT]: Bono makes a massive save to deny Canada. Morocco is clinging to their lead.",
  89: "[ORACLE]: Goalkeeper rating for Bono upgraded. He is single-handedly preserving the win.",
  90: "[SCOUT]: Players are slowing the pace down with short passes to waste time.",
  91: "[SCOUT]: The referee plays advantage after a slight foul in the center circle.",
  92: "[ORACLE]: Analyzing time-wasting tactics. The ball is out of play for an average of 45 seconds per stoppage.",
  93: "[SCOUT]: A long ball is played forward but it goes out for a goal kick.",
  94: "[SCOUT]: The defensive line pushes up to catch the attackers offside.",
  95: "[SCOUT]: Full time whistle! Morocco wins 2-1 and advances to the knockout stages!",
  96: "[ORACLE]: Match concluded. Final analysis complete. Logging predictive accuracy to the ledger."
};
